
name: build-app
on:
  pull_request:
    branches:
      - 'develop'

  push:
    branches:
      - 'feature/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvmrc.outputs.node_version }}'
          cache: 'yarn'
      - name: Frontend Build
      - working-directory: ./frontend
      - run: yarn install
      - run: yarn build
      - name: Backend Build
      - working-directory: ./backend
      - run: yarn install
      - run: yarn build

