name: CreateRelease

on:
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  build:
    name: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: zendesk/action-create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_schema: semantic
  publish:    
    runs-on: ubuntu-latest
    needs: build 
    steps:
      - uses: actions/checkout@v2
      - uses: lakto/gren-action@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          options: '--override'